### ISSUE TITLE
How do I create a polynomial function from an array of coefficients?

### ISSUE THREAD

**Issue by donfung** [Pterodactylus/Ceres.js#1]
Suppose I have a variable array [a1, a2, ..., an] and I'd like to use Ceres.js to compute the roots for f(x) = a1 * x^n + a2 * x^(n-1) + an, how do I create this function to pass to Ceres? I have tried several methods but couldn't find a working solution. The examples seem to only show fixed functions.  

edit: typo

**Comment by srnogueira** [comment]
Have you tried to use arrow functions? Something like this:  `	solver.add_function((x)=>f(a,x,n))`

**Comment by Pterodactylus** [comment]
This shows how the arrow functions can be used to solve in real time.

    `let f = function (x, a, b, c){
        return a*x[0]*x[0] + b*x[0] + c
    }

	let solver = new Ceres()

	solver.promise.then(function(result) { //A promise is necessary to ensure that the Ceres class is loaded.
        let a = -1
        let b = 0
        let c = 9
        solver.add_function((x) => f(x, a, b, c)) //Add the first equation to the solver.
        var x_guess = [1] //Guess the initial values of the solution.
        var s = solver.solve(x_guess) //Solve the equation
        var x = s.x //assign the calculated solution array to the variable x
        document.getElementById("demo").value = s.report + "\n\n" //Print solver report
        solver.reset() // erases the loaded functions and resets the solver.

        a = -2
        b = 1
        c = 9
        solver.add_function((x) => f(x, a, b, c)) //Add the first equation to the solver.
        x_guess = [1] //Guess the initial values of the solution.
        s = solver.solve(x_guess) //Solve the equation
        x = s.x //assign the calculated solution array to the variable x
        document.getElementById("demo").value += s.report //Print solver report

        solver.remove() //required to free the memory in C++
    })`
